Added keywords
schibsted/eslint-config-spt pull request #26
Opened 2016-12-24 17:29 UTC by userpixel

Per [eslint](http://eslint.org/docs/developer-guide/shareable-configs) recommendation:

> We recommend using the eslint and eslintconfig keywords so others can easily find your module.

2016-12-24 21:57 UTC, nosilleg commented
👍

2016-12-24 22:47 UTC, SimenB requested changes
This base config is not published, please put it into the two packages in `packages`.

Not that it hurts here either

2016-12-24 23:36 UTC, userpixel commented
I can fix, but I find it odd that this repo has two published packages. Can we solve the problem in another way @SimenB ?

Have a base config that applies to both browser and node. Let's call it `base`. Then extend it for specific runtimes (like React, Tests, Node, etc. specific) and add some rules on the top.

[ESLint](http://eslint.org/docs/developer-guide/shareable-configs#sharing-multiple-configs) has an interesting solution. Should we give it a try?

2016-12-25 07:51 UTC, SimenB commented
This is modelled after airbnb, the point of two packages are to avoid forcing people not writing react to install `eslint-plugin-react`. Same reason there is both `eslint-config-airbnb` and `eslint-config-airbnb-base`.

2016-12-26 11:23 UTC, ivarconr commented
I think it is great to publish multiple configs as separate modules. Then we don't have to bloat it with tons of config or add stuff you don't need, but er still get to keep all the rules in one repository. After all, many projects does not use react and forcing those rules on everyone makes it harder to use.

2016-12-26 17:33 UTC, userpixel commented
convinced.

2016-12-26 17:43 UTC, userpixel commented
done in master

2016-12-26 17:43 UTC, closed without merging

2016-12-26 19:19 UTC, ivarconr commented
😎